### ISSUE TITLE
Customize

### ISSUE THREAD

**Issue by hansandroid** [bosphere/Android-VerticalSlider#1]
Hi, tell me, please, how can I customize the appearance of the slider under the timeline?

**Comment by bosphere** [comment]
What do you mean by "timeline"? There is no timeline included in the demo.

For possible customisations please refer to https://github.com/bosphere/Android-VerticalSlider#customization.

**Comment by hansandroid** [comment]
Under the timeline, I mean a slider with certain points, for example, like here https://github.com/woxingxiao/BubbleSeekBar/blob/master/screenshot/demo3.gif

**Comment by bosphere** [comment]
This is not currently supported in this library. Feel free to extend beyond what's currently available.
